### ISSUE TITLE
使用注解无法查询到数据

### ISSUE THREAD

**Issue by xxw-git** [dreamyoung/mprelation#2]
![image](https://user-images.githubusercontent.com/52729152/86862394-aec9b380-c0fb-11ea-8d1b-f0fb4024c82e.png)
博主 您好，我在使用@ManyToOne注解时，无法获取到关联数据，是什么原因呢？？
![image](https://user-images.githubusercontent.com/52729152/86862519-efc1c800-c0fb-11ea-9b85-c4b6bb692885.png)

**Comment by xxw-git** [comment]
已解决

**Comment by Koral77** [comment]
> 已解决

老哥，咋解决的
